package modeloH;
// Generated 21/02/2018 18:05:36 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Assistencies generated by hbm2java
 */


public class Assistencies implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer codiAssistencia;
	private Serveis serveis;
	private Usuaris usuaris;
	private Clients clients;
	private Date data;
	private String observacions;

	public Assistencies() {
	}
	//constructor update
	public Assistencies(Integer codiAssistencia, Serveis serveis, Usuaris usuaris, Clients clients, Date data) {
		super();
		this.codiAssistencia = codiAssistencia;
		this.serveis = serveis;
		this.usuaris = usuaris;
		this.clients = clients;
		this.data = data;
	}
	//constructor para interfaz
	public Assistencies(Serveis serveis, Usuaris usuaris, Clients clients, Date data) {
		this.serveis = serveis;
		this.usuaris = usuaris;
		this.clients = clients;
		this.data = data;
	}

	public Assistencies(Serveis serveis, Usuaris usuaris, Clients clients, Date data, String observacions) {
		this.serveis = serveis;
		this.usuaris = usuaris;
		this.clients = clients;
		this.data = data;
		this.observacions = observacions;
	}

	public Integer getCodiAssistencia() {
		return this.codiAssistencia;
	}

	public void setCodiAssistencia(Integer codiAssistencia) {
		this.codiAssistencia = codiAssistencia;
	}

	public Serveis getServeis() {
		return this.serveis;
	}

	public void setServeis(Serveis serveis) {
		this.serveis = serveis;
	}

	public Usuaris getUsuaris() {
		return this.usuaris;
	}

	public void setUsuaris(Usuaris usuaris) {
		this.usuaris = usuaris;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public String getObservacions() {
		return this.observacions;
	}

	public void setObservacions(String observacions) {
		this.observacions = observacions;
	}
	@Override
	public String toString() {
		return "Assistencies [codiAssistencia=" + codiAssistencia + ", serveis=" + serveis.getDescripcio() + ", usuaris=" + usuaris.getIdUsuari()
				+ ", clients=" + clients.getNom() + ", data=" + data + ", observacions=" + observacions + "]";
	}


}
